<a href="https://colab.research.google.com/github/Salonishah06/Portfolio-website/blob/master/Job_Recommendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Dependencies

In [1]:
import numpy as np
import pandas as pd
import difflib 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


Data collection and pre-processing

In [4]:
#loading the data from a csv file to a pandas file
jobs_data = pd.read_csv('/content/jobs.csv')


In [5]:
jobs_data.head()

_id         Date Time                       profile  \
0  5f9fc1e3fb43357b9094a297  02-11-2020 13:52                Fashion Design   
1  5f9fc1e4fb43357b9094a298  02-11-2020 13:52                    Operations   
2  5f9fc1e4fb43357b9094a299  02-11-2020 13:53                   Photography   
3  5f9fc1e5fb43357b9094a29a  02-11-2020 13:53        Social Media Marketing   
4  5f9fc1e6fb43357b9094a29b  02-11-2020 13:53  Business Development (Sales)   

                                 company   Location   Start Date  \
0                                 Enamor  Bangalore  Immediately   
1             Lakshmi Tools & Components    Hoskote  Immediately   
2                   Evineon Technologies  Bangalore  Immediately   
3              VisualNet Private Limited  Bangalore  Immediately   
4  DM Consulting (India) Private Limited  Bangalore  Immediately   

               Stipend  Duration Apply by Date       Offer  ... Unnamed: 11  \
0          5000 /month  2 Months    11 Nov' 20  Internship  ...         NaN   
1         12000 /month   1 Month    16 Nov' 20  Internship  ...         NaN   
2   10000-12000 /month  3 Months    16 Nov' 20  Internship  ...         NaN   
3          7000 /month  6 Months    16 Nov' 20  Internship  ...         NaN   
4          5000 /month  6 Months    16 Nov' 20  Internship  ...         NaN   

  Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15 Unnamed: 16 Unnamed: 17  \
0         NaN         NaN         NaN         NaN         NaN         NaN   
1         NaN         NaN         NaN         NaN         NaN         NaN   
2         NaN         NaN         NaN         NaN         NaN         NaN   
3         NaN         NaN         NaN         NaN         NaN         NaN   
4         NaN         NaN         NaN         NaN         NaN         NaN   

  Unnamed: 18 Unnamed: 19 Unnamed: 20  
0         NaN         NaN         NaN  
1         NaN         NaN         NaN  
2         NaN         NaN         NaN  
3         NaN         NaN         NaN  
4         NaN         NaN         NaN  

[5 rows x 21 columns]

In [60]:
jobs_data['index'] = [i for i in range(0,len(jobs_data.values))]
print(jobs_data.head()) 

                        _id         Date Time                       profile  \
0  5f9fc1e3fb43357b9094a297  02-11-2020 13:52                Fashion Design   
1  5f9fc1e4fb43357b9094a298  02-11-2020 13:52                    Operations   
2  5f9fc1e4fb43357b9094a299  02-11-2020 13:53                   Photography   
3  5f9fc1e5fb43357b9094a29a  02-11-2020 13:53        Social Media Marketing   
4  5f9fc1e6fb43357b9094a29b  02-11-2020 13:53  Business Development (Sales)   

                                 company   Location   Start Date  \
0                                 Enamor  Bangalore  Immediately   
1             Lakshmi Tools & Components    Hoskote  Immediately   
2                   Evineon Technologies  Bangalore  Immediately   
3              VisualNet Private Limited  Bangalore  Immediately   
4  DM Consulting (India) Private Limited  Bangalore  Immediately   

               Stipend  Duration Apply by Date       Offer  ... Unnamed: 12  \
0          5000 /month  2 Months    1

In [61]:
#selecting the relevant features 
selected_features= ['_id','profile','Location','Skills and Perks','Apply by Date']
print(selected_features)

['_id', 'profile', 'Location', 'Skills and Perks', 'Apply by Date']


In [62]:
#replacing the null values
for feature in selected_features :
  jobs_data[feature]=jobs_data[feature].fillna('')

In [63]:
#combining the 5 features
combined_features= jobs_data['_id']+jobs_data['profile']+jobs_data['Location']+jobs_data['Skills and Perks']+jobs_data['Stipend']

In [64]:
print(combined_features)

0       5f9fc1e3fb43357b9094a297Fashion DesignBangalor...
1       5f9fc1e4fb43357b9094a298OperationsHoskote["Che...
2       5f9fc1e4fb43357b9094a299PhotographyBangalore["...
3       5f9fc1e5fb43357b9094a29aSocial Media Marketing...
4       5f9fc1e6fb43357b9094a29bBusiness Development (...
                              ...                        
2995    5f9fc6b25ae1fc3c5cd0d126Business Development (...
2996    5f9fc6b35ae1fc3c5cd0d127Mobile App Development...
2997    5f9fc6b55ae1fc3c5cd0d128Human Resources (HR)Th...
2998    5f9fc6b75ae1fc3c5cd0d129Full-stack Development...
2999    5f9fc7ce75696fcdf0e25d50Business Development (...
Length: 3000, dtype: object


In [65]:
#converting the text data into feature vectors
vectorizer=TfidfVectorizer()

In [66]:
feature_vectors=vectorizer.fit_transform(combined_features)

In [67]:
print(feature_vectors)

  (0, 3659)	0.08073982237621509
  (0, 52)	0.18725603863060386
  (0, 3226)	0.08837296833407893
  (0, 3275)	0.35613689272187976
  (0, 3507)	0.2943392706760189
  (0, 3078)	0.23927764677366453
  (0, 3688)	0.25460162915807555
  (0, 3664)	0.19916905011718472
  (0, 3306)	0.3986479227587435
  (0, 1377)	0.6453472896566911
  (1, 8)	0.27993101638130613
  (1, 3189)	0.21636140825679454
  (1, 3864)	0.21636140825679454
  (1, 3462)	0.21636140825679454
  (1, 3246)	0.14709218979758393
  (1, 3359)	0.14715569385460522
  (1, 3520)	0.14715569385460522
  (1, 3770)	0.10574535549909124
  (1, 3686)	0.10555956984168571
  (1, 3575)	0.10574535549909124
  (1, 3231)	0.5046544074775429
  (1, 1378)	0.643300198215365
  (1, 3659)	0.08048370942430594
  (1, 3226)	0.08809264245370292
  (2, 2)	0.22452397706130467
  :	:
  (2998, 17)	0.16647980543285412
  (2998, 2)	0.12318961984270307
  (2998, 3189)	0.13863377408016614
  (2998, 3864)	0.13863377408016614
  (2998, 3462)	0.13863377408016614
  (2998, 3246)	0.09424945776444765
  (

Cosine Similarity


In [68]:
#getting the similarity scores by using cosine similarity
similarity=cosine_similarity(feature_vectors)

In [69]:
print(similarity)

[[1.         0.01428325 0.00758881 ... 0.04728245 0.00416375 0.01425246]
 [0.01428325 1.         0.26308274 ... 0.04584975 0.13574957 0.04764199]
 [0.00758881 0.26308274 1.         ... 0.00726446 0.13759289 0.07416057]
 ...
 [0.04728245 0.04584975 0.00726446 ... 1.         0.0039858  0.09813774]
 [0.00416375 0.13574957 0.13759289 ... 0.0039858  1.         0.0041416 ]
 [0.01425246 0.04764199 0.07416057 ... 0.09813774 0.0041416  1.        ]]


In [70]:
print(similarity.shape)

(3000, 3000)


In [78]:
#getting the name of the jobs 
jobs_name=input('Enter the job you are seeking: ') 

Enter the job you are seeking: Digital Marketing


In [79]:
#creating a list with all the jobs given in the dataset
list_of_all_profiles=jobs_data['profile'].tolist()
print(list_of_all_profiles)


['Fashion Design', 'Operations', 'Photography', 'Social Media Marketing', 'Business Development (Sales)', 'Social Media Marketing', 'Event Management/Wedding Planning', 'Digital Marketing', 'Graphic Design', 'Cyber Security', 'Business Development (Sales)', 'Business Development (Sales)', 'Java App Development (Spring Boot & Hibernate)', 'Python Web Application', 'Graphic Design', 'Search Engine Optimization (SEO)', 'Social Media Marketing', 'Human Resources (HR)', 'Graphic Design', 'Social Media Marketing', 'Business Development (Sales)', 'Law/ Legal', 'iOS App Development', 'Business Development (Sales)', 'Customer Support', 'Business Development (Sales)', 'Firmware Development', 'Operations', 'Marketing', 'Human Resources (HR)', 'Business Development (Sales)', 'Business Development (Sales)', 'Operations', 'Graphic Design', 'Human Resources (HR)', 'Digital Marketing', 'Marketing', 'Business Development (Sales)', 'Online Marketing', 'Graphic Design', 'Graphic Design', 'Career Returnee

In [80]:
#finding the close match 
find_close_match=difflib.get_close_matches(jobs_name,list_of_all_profiles)
print(find_close_match)


['Digital Marketing', 'Digital Marketing', 'Digital Marketing']


In [81]:
close_match=find_close_match[0]
print(close_match)

Digital Marketing


In [82]:
index_of_the_job=jobs_data[jobs_data.profile == close_match]["index"].values[0]
print(index_of_the_job)


7


In [85]:
#getting the list of similar movies
similarity_score=list(enumerate(similarity[index_of_the_job]))
print(similarity_score)

[(0, 0.04971775373116488), (1, 0.2555997727830134), (2, 0.17324612319751512), (3, 0.3869460635389158), (4, 0.0510816740703283), (5, 0.33257024711742506), (6, 0.03286682140649278), (7, 1.0000000000000002), (8, 0.1699594204077079), (9, 0.027341415977414324), (10, 0.013932757438445013), (11, 0.09694124090072948), (12, 0.11926956893322262), (13, 0.1628145338910958), (14, 0.027078477652270762), (15, 0.202333111734478), (16, 0.39825067643547885), (17, 0.012858037948709135), (18, 0.10555825673633956), (19, 0.21662816837539758), (20, 0.1168770765104231), (21, 0.045322408622803276), (22, 0.03650724966617926), (23, 0.23612728863212587), (24, 0.2307951687499181), (25, 0.01624212716823213), (26, 0.01033971033089329), (27, 0.009262512993883712), (28, 0.053087897365390914), (29, 0.04836632501079477), (30, 0.01720218294019525), (31, 0.24225319599973305), (32, 0.10523158214655684), (33, 0.0573102831579526), (34, 0.08491134999711505), (35, 0.28600061063756305), (36, 0.23171949901506203), (37, 0.0165661

In [86]:
len(similarity_score)

3000

In [87]:
sorted_similar_jobs= sorted(similarity_score,key= lambda x:x[1], reverse=True)
print(sorted_similar_jobs)

[(7, 1.0000000000000002), (208, 0.40510997516574904), (16, 0.39825067643547885), (3, 0.3869460635389158), (464, 0.3772480520804318), (159, 0.37218823857686173), (2466, 0.36733861026199094), (1115, 0.3601540814484698), (1743, 0.35546609833793597), (252, 0.3524334704568551), (839, 0.35167659268804025), (207, 0.3506361286785772), (690, 0.3489475730463264), (256, 0.3483912206006444), (373, 0.336201825360416), (266, 0.3361937663741697), (1117, 0.3355162709192821), (1108, 0.3350513604771315), (1954, 0.33431559627972474), (2762, 0.3337774569506028), (5, 0.33257024711742506), (439, 0.3304292498632801), (2063, 0.3247121394856698), (2868, 0.32468045826964353), (1062, 0.3236374349317713), (831, 0.321457651554092), (190, 0.31963310081690155), (152, 0.3159139104438332), (102, 0.3157182185460687), (2412, 0.311986167463274), (121, 0.3108428908795891), (209, 0.310220385408597), (475, 0.3085587819972686), (1082, 0.3082050763832368), (1380, 0.3080832450060526), (129, 0.3075400462186934), (558, 0.3067860

In [88]:
i=1
for jobs in sorted_similar_jobs:
  index=jobs[0]
  profile_from_index= jobs_data[jobs_data.index==index]['profile'].values[0]
  if(i<30):
    print(i,'',profile_from_index)
    i+=1


1  Digital Marketing
2  Digital Marketing
3  Social Media Marketing
4  Social Media Marketing
5  Digital Marketing
6  Social Media Marketing
7  Social Media Marketing
8  Social Media Marketing
9  Marketing
10  Social Media Marketing
11  Social Media Marketing
12  Digital Marketing
13  Digital Marketing
14  Social Media Marketing
15  Digital Marketing
16  Digital Marketing
17  Business Development (Sales)
18  Business Development (Sales)
19  Content Writing
20  Cinematography
21  Social Media Marketing
22  Social Media Marketing
23  Digital Marketing
24  Marketing
25  Digital Marketing
26  Social Media Marketing
27  Digital Marketing
28  Marketing
29  Social Media Marketing


In [98]:
#Job Recommendation System:
jobs_name=input('Enter the job you are seeking: ')

list_of_all_profiles=jobs_data['profile'].tolist()

find_close_match=difflib.get_close_matches(jobs_name,list_of_all_profiles)

close_match=find_close_match[0]

index_of_the_job=jobs_data[jobs_data.profile == close_match]["index"].values[0]

similarity_score=list(enumerate(similarity[index_of_the_job]))

sorted_similar_jobs= sorted(similarity_score,key= lambda x:x[1], reverse=True)

print('Suggested Jobs are as follows:\n')

i=1
for jobs in sorted_similar_jobs:
  index=jobs[0]
  profile_from_index= jobs_data[jobs_data.index==index]['profile'].values[0]
  if(i<60):
    print(i,'',profile_from_index)
    i+=1


Enter the job you are seeking: Development
Suggested Jobs are as follows:

1  UI Development
2  Web Development
3  Web Development
4  Web Development
5  Business Development
6  Full Stack Development
7  Mobile App Development
8  Web Development
9  Web Development
10  Android/Flutter App Development
11  Python Web Application
12  PHP Development
13  PHP Development
14  Web Development
15  Web Development
16  Web Development
17  Web Development
18  Mobile App Development
19  Web Development
20  Web Development
21  Business Development
22  Web Development
23  Web Development
24  PHP Development
25  Web Development
26  Android App Development
27  Mobile App Development
28  Graphic Design
29  Content Writing
30  Operations
31  Mobile App Development
32  Web Development
33  Mobile App Development
34  Business Development
35  Operations
36  Web Development
37  Full Stack Development
38  Python Development
39  Operations
40  Mobile App Development
41  Web Development
42  Web Development
43  We